/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin.route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeusBilhetesRouteImport } from './routes/meus-bilhetes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBilhetesRouteImport } from './routes/admin/bilhetes'
import { Route as AdminMercadosRouteImport } from './routes/admin/mercados'
import { Route as AdminOddsRouteImport } from './routes/admin/odds'
import { Route as AdminResultadosRouteImport } from './routes/admin/resultados'
import { Route as JogoFixtureIdRouteImport } from './routes/jogo.$fixtureId'
import { Route as PagamentoTicketIdRouteImport } from './routes/pagamento.$ticketId'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api.public.asaas-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusBilhetesRoute = MeusBilhetesRouteImport.update({
  id: '/meus-bilhetes',
  path: '/meus-bilhetes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBilhetesRoute = AdminBilhetesRouteImport.update({
  id: '/bilhetes',
  path: '/bilhetes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMercadosRoute = AdminMercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOddsRoute = AdminOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResultadosRoute = AdminResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AdminRouteRoute,
} as any)
const JogoFixtureIdRoute = JogoFixtureIdRouteImport.update({
  id: '/jogo/$fixtureId',
  path: '/jogo/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoTicketIdRoute = PagamentoTicketIdRouteImport.update({
  id: '/pagamento/$ticketId',
  path: '/pagamento/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/meus-bilhetes': typeof MeusBilhetesRoute
  '/perfil': typeof PerfilRoute
  '/admin/bilhetes': typeof AdminBilhetesRoute
  '/admin/mercados': typeof AdminMercadosRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/jogo/$fixtureId': typeof JogoFixtureIdRoute
  '/pagamento/$ticketId': typeof PagamentoTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/meus-bilhetes': typeof MeusBilhetesRoute
  '/perfil': typeof PerfilRoute
  '/admin/bilhetes': typeof AdminBilhetesRoute
  '/admin/mercados': typeof AdminMercadosRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/jogo/$fixtureId': typeof JogoFixtureIdRoute
  '/pagamento/$ticketId': typeof PagamentoTicketIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/meus-bilhetes': typeof MeusBilhetesRoute
  '/perfil': typeof PerfilRoute
  '/admin/bilhetes': typeof AdminBilhetesRoute
  '/admin/mercados': typeof AdminMercadosRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/jogo/$fixtureId': typeof JogoFixtureIdRoute
  '/pagamento/$ticketId': typeof PagamentoTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/meus-bilhetes'
    | '/perfil'
    | '/admin/bilhetes'
    | '/admin/mercados'
    | '/admin/odds'
    | '/admin/resultados'
    | '/jogo/$fixtureId'
    | '/pagamento/$ticketId'
    | '/admin/'
    | '/api/public/asaas-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/meus-bilhetes'
    | '/perfil'
    | '/admin/bilhetes'
    | '/admin/mercados'
    | '/admin/odds'
    | '/admin/resultados'
    | '/jogo/$fixtureId'
    | '/pagamento/$ticketId'
    | '/admin'
    | '/api/public/asaas-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/meus-bilhetes'
    | '/perfil'
    | '/admin/bilhetes'
    | '/admin/mercados'
    | '/admin/odds'
    | '/admin/resultados'
    | '/jogo/$fixtureId'
    | '/pagamento/$ticketId'
    | '/admin/'
    | '/api/public/asaas-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  MeusBilhetesRoute: typeof MeusBilhetesRoute
  PerfilRoute: typeof PerfilRoute
  JogoFixtureIdRoute: typeof JogoFixtureIdRoute
  PagamentoTicketIdRoute: typeof PagamentoTicketIdRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-bilhetes': {
      id: '/meus-bilhetes'
      path: '/meus-bilhetes'
      fullPath: '/meus-bilhetes'
      preLoaderRoute: typeof MeusBilhetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bilhetes': {
      id: '/admin/bilhetes'
      path: '/bilhetes'
      fullPath: '/admin/bilhetes'
      preLoaderRoute: typeof AdminBilhetesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mercados': {
      id: '/admin/mercados'
      path: '/mercados'
      fullPath: '/admin/mercados'
      preLoaderRoute: typeof AdminMercadosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/odds': {
      id: '/admin/odds'
      path: '/odds'
      fullPath: '/admin/odds'
      preLoaderRoute: typeof AdminOddsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resultados': {
      id: '/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AdminResultadosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/jogo/$fixtureId': {
      id: '/jogo/$fixtureId'
      path: '/jogo/$fixtureId'
      fullPath: '/jogo/$fixtureId'
      preLoaderRoute: typeof JogoFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$ticketId': {
      id: '/pagamento/$ticketId'
      path: '/pagamento/$ticketId'
      fullPath: '/pagamento/$ticketId'
      preLoaderRoute: typeof PagamentoTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBilhetesRoute: typeof AdminBilhetesRoute
  AdminMercadosRoute: typeof AdminMercadosRoute
  AdminOddsRoute: typeof AdminOddsRoute
  AdminResultadosRoute: typeof AdminResultadosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBilhetesRoute: AdminBilhetesRoute,
  AdminMercadosRoute: AdminMercadosRoute,
  AdminOddsRoute: AdminOddsRoute,
  AdminResultadosRoute: AdminResultadosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  MeusBilhetesRoute: MeusBilhetesRoute,
  PerfilRoute: PerfilRoute,
  JogoFixtureIdRoute: JogoFixtureIdRoute,
  PagamentoTicketIdRoute: PagamentoTicketIdRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
