// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imxucsmfxrxfglkbqrqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlteHVjc21meHJ4Zmdsa2JxcnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3OTM4MDksImV4cCI6MjEwMTM2OTgwOX0.0Z4r3obR6lFegbKzrY5Fu9A_pVOq_xhP8Po0eoeEG5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});